[package]
name = "photovault-exif"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
photovault-core = { workspace = true }
little_exif = "0.6"
kamadak-exif = "0.6"
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
