[package]
name = "photovault-restore"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
photovault-core = { workspace = true }
photovault-catalog = { workspace = true }
photovault-google = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
sqlx = { workspace = true }
